 * Serving Flask app 'app'
 * Debug mode: on
Traceback (most recent call last):
  File "/home/zealot/Public/Nexascale/app-deployment-task/messaging/app.py", line 14, in <module>
    logging.basicConfig(
  File "/usr/lib/python3.12/logging/__init__.py", line 2118, in basicConfig
    h = FileHandler(filename, mode,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/logging/__init__.py", line 1231, in __init__
    StreamHandler.__init__(self, self._open())
                                 ^^^^^^^^^^^^
  File "/usr/lib/python3.12/logging/__init__.py", line 1263, in _open
    return open_func(self.baseFilename, self.mode,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/var/log/messaging_system.log'
Traceback (most recent call last):
  File "/home/zealot/Public/Nexascale/app-deployment-task/messaging/app.py", line 4, in <module>
    from task import send_email  # Import Celery task
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zealot/Public/Nexascale/app-deployment-task/messaging/task.py", line 19, in <module>
    logging.basicConfig(
  File "/usr/lib/python3.12/logging/__init__.py", line 2118, in basicConfig
    h = FileHandler(filename, mode,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/logging/__init__.py", line 1231, in __init__
    StreamHandler.__init__(self, self._open())
                                 ^^^^^^^^^^^^
  File "/usr/lib/python3.12/logging/__init__.py", line 1263, in _open
    return open_func(self.baseFilename, self.mode,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/var/log/messaging_system.log'
 * Serving Flask app 'app'
 * Debug mode: off
 * Serving Flask app 'app'
 * Debug mode: off
Address already in use
Port 5000 is in use by another program. Either identify and stop that program, or start the server with a different port.
 * Serving Flask app 'app'
 * Debug mode: off
Address already in use
Port 5000 is in use by another program. Either identify and stop that program, or start the server with a different port.
Traceback (most recent call last):
  File "/home/zealot/Public/Nexascale/app-deployment-task/messaging/test.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
 * Serving Flask app 'app'
 * Debug mode: off
Address already in use
Port 5000 is in use by another program. Either identify and stop that program, or start the server with a different port.
Traceback (most recent call last):
  File "/home/zealot/Public/Nexascale/app-deployment-task/messaging/test.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "/home/zealot/Public/Nexascale/app-deployment-task/messaging/app.py", line 4, in <module>
    from task import send_email  # Import Celery task
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zealot/Public/Nexascale/app-deployment-task/messaging/task.py", line 13, in <module>
    raise ValueError("EMAIL_HOST_USER or EMAIL_HOST_PASSWORD not set in environment")
ValueError: EMAIL_HOST_USER or EMAIL_HOST_PASSWORD not set in environment
Traceback (most recent call last):
  File "/home/zealot/Public/Nexascale/app-deployment-task/messaging/test.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
 * Serving Flask app 'app'
 * Debug mode: off
Address already in use
Port 5000 is in use by another program. Either identify and stop that program, or start the server with a different port.
Traceback (most recent call last):
  File "/home/zealot/Public/Nexascale/app-deployment-task/messaging/test.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "/home/zealot/Public/Nexascale/app-deployment-task/messaging/test.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
